### ISSUE TITLE
Address format?

### ISSUE THREAD

**Issue by teran-mckinney** [AustEcon/bitsv#11]
`.address` seems to return in the cashaddr format. Is that correct?

Integrating this in walkingliberty.

**Comment by AustEcon** [comment]
That's awesome.

Yes. That sounds about right. It needs work in that department.

The intention is to change it all back to Legacy format to be same as everyone else on bsv network/apis etc but will probably have to bump to 0.7.0 because will break ppl's code.

I also want to do a breaking change to my latest bip32 support stuff to choose better variable names and make it more intuitive to use. I just banged it out quickly because I was having requests for it...

**Comment by AustEcon** [comment]
Probably. Can't be sure though. Not at my PC. About to start the work day... do you think so? I guess this is where the testing modules come in handy :)

**Comment by teran-mckinney** [comment]
I could understand someone wanting a `bitcoinsv:q...` format, but not `bitcoincash:q...` format. Personally, I think this should be fairly safe. If someone wants to be certain nothing will break, they should be pinning versions anyway.

I'll have a look at this and see. Most stuff that has cashaddr support supports both.

**Comment by AustEcon** [comment]
Thanks. 
I put out a small message in _unwriter's slack... sounds like it should be fine / recommended to pretty rapidly remove the cashaddr format altogether... 
I'm planning a big weekend of coding...

**Comment by teran-mckinney** [comment]
Great, no problem. Do you think you can make a new pip release soon?

I have the WalkingLiberty changes together but just wanted to have the address format standardized before using it.

**Comment by AustEcon** [comment]
No problem. I'll likely be able to do it today.

**Comment by AustEcon** [comment]
@teran-mckinney I have just put out a new release 0.7.1

**Comment by teran-mckinney** [comment]
Great, thank you!

**Comment by AustEcon** [comment]
I just saw this on
bottle... B://fd0a393807e8ba88c7c7470175ed7cecfbcdc111d827af013e9f351bb4548b49

Nice :) I have just started to sink my teeth into some of _unwriter's
protocols now. Successfully uploaded an image following the b:// and c://
protocols just now.
