### ISSUE TITLE
Cutting a new release

### ISSUE THREAD

**Issue by teran-mckinney** [AustEcon/bitsv#34]
Would be nice to cut a new release with the rates API. However, it still won't install on 3.5 with bitcoinX.

Do you think it's doable to move bip32 out to its own repository? Another possibility is fixing 3.5 support in bitcoinX, but it seems to depend on electrumSV which also uses f-strings, so seems like quite the thing to chase down.

I tried moving my stuff over to Debian Buster which has Python 3.7, but that was a whole can of worms. Made some headway, but think I want to wait until the next Saltstack release and ideally a minor release or two on 10.

**Comment by teran-mckinney** [comment]
Exploring the 0.7.1 tree, it looks like there was no requirement for bitcoinX but you had bip32? Was that a mistake?

In this case, a release would break Python 3.5 systems but 0.7.1 will install just fine.

By the way, in requirements.txt `-e .` means refer to setup.py and you can list all the dependencies in there.

**Comment by AustEcon** [comment]
It shouldn't take too much for me to get all of this done. Would like to release with updated documentation ideally because a fair bit has changed but I can put in a big effort this week! 

I want to get all of these things done asap anyway. Will feel good to have it done. 😁

Let's aim to do a new release by the end of the weekend. I'll keep you posted!

**Comment by teran-mckinney** [comment]
Ok, sounds great! Thank you!!

**Comment by joshua-s** [comment]
0.8.0 was just released and is now available on PyPi

Release Notes: https://github.com/AustEcon/bitsv/releases/tag/0.8.0
