### ISSUE TITLE
0.9.0 Release

### ISSUE THREAD

**Issue by teran-mckinney** [AustEcon/bitsv#43]
Todo:

 * Update README.md

Anything else that we should do before then?

**Comment by AustEcon** [comment]
I think I'd like to do a simple little fix to the TxOutput dataclass. Because otherwise you get an ugly error message when iterating over anything that is not a simple utf-8 OP_RETURN message...

I think I will keep it **really** simple and just add an if statement that goes:
- if utf-8 message --> decode
- else --> represent it as raw bytes...

My current inclination on it is to make a design decision here about the scope of bitsv and rather than keep adding more and more... to build ontop of this in polyglot... and have a growing list of recognized OP_RETURN data types e.g.:
- B://
- BCAT://
etc.
and the various multimedia types within that... for downloading and decoding...

I plan to create a "download.py" file in polyglot as the counterpart to the current upload.py. In it there will be a "Download" class for all of this stuff ^^.

**Comment by teran-mckinney** [comment]
I like this, agreed on all counts about the logic and polyglot.

Not sure if you've heard the acronym before, but KISS :).

**Comment by AustEcon** [comment]
Actually, there would be no way to know how the op_return is encoded so I'll leave that responsibility to the user and probably just make it hex.

Could maybe have an added luxury of parsing the pushdata op_codes and returning the hex bytes as a separated list... I think that would be more noob friendly...

**Comment by teran-mckinney** [comment]
I think I would send it as raw bytes. Converting to hex and back is slower and odds are that's what they'd be doing. I think someone working with RETURN is going to have to know what they're doing to some extent. polyglot can make it easy, though :).

Separate list might make sense, are you saying if there's multiple OP_RETURNs?

**Comment by AustEcon** [comment]
The api gives hex though so might be faster?

I mean a list of pushdata parts **within** the op_return... to save people that headache...

**Comment by teran-mckinney** [comment]
Hmm, I see. In that case maybe the string hex is fine. Although then we need to expect all APIs to return it in that format, or convert it if it's not.

**Comment by AustEcon** [comment]
Yeah. But in my experience so far. All API's return op return data as hex

**Comment by teran-mckinney** [comment]
No problem in that case. Sounds good with me!
